### PR TITLE
Use spanned error for the regex flag as well

### PR DESCRIPTION
**Pull request by necauqua**
Can't believe I missed that one panic :sweat_smile:
Also made it to point exactly at the bad flag on nightly (where the subspan api only works for now)

### CODE REVIEW

**Comment by Canop** [comment]
You missed also 2 useless closures that clippy checked ;)

**Comment by Canop** [comment]
I have to change the version of syn: old 1.0 don't have the `token()` function in LitStr.

**Comment by Canop** [comment]
If you don't find anything new, I'll try to release that in 2.3.1 tomorrow

**Comment by necauqua** [comment]
oof, looks like my rust-analyzer config in helix was borked so clippy hints were not there

Yeah, I don't think there's anything new after that, thanks! :)

Oh wait I don't think pinning `syn` minor version was correct - if worked for me, it's just that your local version of syn in `Cargo.lock` was too old, `cargo update` would've fixed this.

**Comment by Canop** [comment]
It's not really pinning: later minor versions are considered acceptable too, so I see no downside in saying we need at least some version.

**Comment by Canop** [comment]
@necauqua spanned errors went live in 2.3.1

**Pull request merged**
