### PR TITLE
Add no_std support

### PR DESCRIPTION
**Pull request by TTWNO**

### CODE REVIEW

**Comment by TTWNO** [comment]
Fix #34

**Comment by Canop** [comment]
(fix #29, not #34)

**Comment by Canop** [comment]
I'm not familiar with `no_std`.

> If you need to use this crate in a `no_std` environment, you must enable the "critical-section" feature.

Is that really a "must enable", or rather something like "should enable for a potentially better locking" ? Can you better explain the reasoning ?

**Comment by TTWNO** [comment]
To perform locking operations on embedded targets (i.e., ones with no standard library/no `std::*`), you will need your own locking mechanism.  Critical section provides this.

**Pull request merged**
